name: Pipeline Datos Clima Latam

on: 
  push:
    branches: [main]
  schedule:
  - cron: '0 9 * * 1' # Ejecutar cada lunes a las 9:00 AM
  workflow_dispatch:

jobs:
  build-and-run:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: '10.0.x'

    - name: Restore dependencies
      run: dotnet restore
    - name: Build the project
      run: dotnet build ClimaLatamPipeline/ClimaLatamPipeline.csproj --configuration Release
    
    - name: Run the project
      env:
        NEON_CONNECTION_STRING: ${{ secrets.NEON_CONNECTION_STRING }}
      run: dotnet run --project ClimaLatamPipeline/ClimaLatamPipeline.csproj --no-build

